# Numpy

Numpy is a library which provides support for large, homogenous, multi dimensional arrays and matrices.

In [8]:
#import numpy
import numpy as np 

## Creating Arrays in Numpy
### Creating an array from a list

In [6]:
list1 = [10,20,30]

In [14]:
print(list1)
list1

[10, 20, 30]


[10, 20, 30]

In [9]:
arr1 = np.array(list1)

In [10]:
print(arr1)

[10 20 30]


In [11]:
arr1

array([10, 20, 30])

In [12]:
type(arr1)

numpy.ndarray

### using arrange to create an array 

The difference between array and arrange is that array takes in a list and turn it into an array, whereas arange creates an array from a range of numbers.

In [15]:
arr2 = np.arange(10,20,1) # (start,stop,step size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays


### Combining two list - Two Dimensional arrays

When we combine arrays together, we can add dimension. Combining two arrays gives us a 2d array.

This creates a matric for us on which we can perform matrix operations.

In [16]:
#lets create a new list to join onto the first list 
list2 = [40,50,60]

#join the lists
list3 = [list1, list2]

#create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
#lets find the shape of that array
#we have a 2d array with 2 elements in the first instance and 3 in the second 
arr3.shape 

(2, 3)

### Three dimensional arrays

In [62]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim
arr3dim.shape

(2, 2, 3)

## Using Arrays and scalars

Numpy arrays (or ndarray) allow us to perform matrix operations

In [63]:
#for example, we can use simple multiplication 
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [24]:
#How is this different than trying to do:
list1 * 3
#Lists and arrays are treated differently see below:

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [64]:
# We can actually multiply an array with another array 

# create a new array with the same size as arr1
arr1 = np.array

In [32]:
### Can we multiple arrays of different shapes?

### It is possible to multiple arrays of different dimension, but they need the same element size

In [65]:
arr1 * arr3dim 

TypeError: unsupported operand type(s) for *: 'builtin_function_or_method' and 'int'

### NEW TASK

In [34]:
#One dimensional array with 12 elements (12,) 
arr7ask = np.arange(1,13,1) # (start,stop,step size)
arr7ask

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
#Two dimensional array size (3, 4)

#create our first list
list_x = [100,200,300,400]

#create our second list
list_c = [500,501,502,503]

#join the lists
list_v = [list_x, list_c,]

#create an array out of the joined lists
arr3 = np.array(list_v)
arr3

array([[100, 200, 300, 400],
       [500, 501, 502, 503]])

In [36]:
#lets find the shape of that array
#we have a 3d array with 3 elements in the first instance and 4 in the second 
arr3.shape 

(3, 4)

In [37]:
#Three dimensional array size (2, 5, 4)

### Accessing the values inside ndarrays

lets take arr3 as our example, this was a 2d array

In [39]:
arr3

array([[100, 200, 300, 400],
       [500, 501, 502, 503]])

In [40]:
# how can we access the 502

# we can use indexing
arr3[1][2]

#we can just use a comma
arr3[1,2]


502

In [41]:
# How can I get the bottom row of this ndarray
arr3[1]

array([500, 501, 502, 503])

In [42]:
#How about if we just want the last COLUMN
#: Means everything, so see below:
arr3[:,2]

array([300, 502])

## Statistical  functions and arrays

There are a number of builtin functions we can use with numpy

In [43]:
# Finding the sum of all values
arr3.sum()

3006

In [44]:
# Finding the sum od all columns
arr3.sum(0)

array([600, 701, 802, 903])

In [45]:
# Finding the sum of all rows
arr3.sum(1)

array([1000, 2006])

In [46]:
# Finding the mean
arr3.mean()

375.75

In [47]:
#Finding standard deviation
arr3.std()

148.53850510894472

In [48]:
# Finding variance 
arr3.var()

22063.6875

In [50]:
# Finding min
arr3.min()

100

In [51]:
#finding max value
arr3.max()

503

## Iterating through ndarrays 

simplest way is to use a simmple loop

In [52]:
# For a 1d array
for x in arr1:
    print(x)

10
20
30


In [53]:
# How about an n-dimensional array? Use nested loops

for dim in arr3:
    for num in dim:
        print (num)

100
200
300
400
500
501
502
503


In [54]:
#There is another way, use nditer
# this can be used in simple scenarios, but also very complex ones

# It tends to be much cleaner for nested loops
for x in np.nditer(arr3):
    print(x)

100
200
300
400
500
501
502
503


### Saving and loading in numpy 

In [55]:
# To save an array as a file
np.save("new", arr3)

In [57]:
# Load the file
np.load("new.npy")

array([[100, 200, 300, 400],
       [500, 501, 502, 503]])

In [59]:
#saving as a txt, delimiter lets us know how our datas stored.
np.savetxt("new.txt", arr3, delimiter=",") 

In [60]:
# Loading a txt 
np.loadtxt("new.txt", delimiter=",")

array([[100., 200., 300., 400.],
       [500., 501., 502., 503.]])